name: Build and deploy container app to Azure Web App - faros-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./lighthouse-backend

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_2afb8b6a9eed492d8c20c83a9ede8481 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_78c2424a8f8240f0863bf67204709e52 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.AzureAppService_ContainerUsername_2afb8b6a9eed492d8c20c83a9ede8481 }}/faluciano/faros-backend:${{ github.sha }}
          file: lighthouse-backend/dockerfile # Ensure this path is correct
          context: ./lighthouse-backend # Added context to specify build directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "faros-backend"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_140473bef51b4b42abc323aa8d968cc9 }}
          images: ${{ secrets.AzureAppService_ContainerUsername_2afb8b6a9eed492d8c20c83a9ede8481 }}/faros-backend:${{ github.sha }}
